apiVersion: v1
kind: ConfigMap
metadata:
  name: kf-config-mut
  namespace: cpp
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address: 
          socket_address:
            address: 0.0.0.0
            port_value: 10000          
        filter_chains:
        - filters:
          - name: envoy.filters.network.kafka_broker
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
              stat_prefix: exampleprefix1
              # force_response_rewrite: true
              id_based_broker_address_rewrite_spec:
                rules:
                - id: 0
                  host: kf-tls-stand-pods.cpp.svc.cluster.local
                  port: 9092
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: broker1cluster
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                - certificate_chain:
                    filename: server/tls.crt
                  private_key:
                    filename: server/tls.key
          
      clusters:
      - name: broker1cluster
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: some_service
          endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: kf-tls.cpp.svc.cluster.local
                      port_value: 29092
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain:
                  filename: client/tls.crt
                private_key:
                    filename: client/tls.key
              # validation_context: 
              #   trusted_ca: 
              #     filename: /home/user/office/kf-test/kf-client-ca-1.crt
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
